version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ${DB_PROJ_DIR:-.}/dataset:/docker-entrypoint-initdb.d
    ports:
     - 5432:5432
    
  
  # mongo:
  #   image: mongo
  #   ports:
  #     - 27017:27017